# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'alalami' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for alalami
  pod 'Alamofire'
  pod 'MOLH'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SVProgressHUD'
  pod 'Kingfisher', '~> 5.0'
  pod 'AlamofireImage', '~> 3.5'
  pod 'BRYXBanner'
  pod 'IQKeyboardManagerSwift'
  pod 'FittedSheets'
  pod 'MultilineTextField'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'CBPinEntryView'
  pod 'DatePickerDialog'
  pod 'SwiftDate', '~> 6.0.0'
  pod 'KeychainAccess'
  pod 'CountryPickerView'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'DropDown'
  pod "SwiftyCam"
  pod 'ImageTransition'
  pod 'PTTimer'
  pod 'netfox'
  pod "Sheeeeeeeeet"
  pod 'TagListView', '~> 1.0'
  pod 'MaterialComponents'
  pod "SimpleAnimation"
  pod 'JJFloatingActionButton'
  pod 'PMAlertController'
  pod 'EMAlertController'
  pod 'TCCopyableLabel'
  
 
end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'





end
end
end
